jobs:
  build:
    docker:
      - image: cranphin/iverilog
    steps:
      - checkout
      - run: cd src
      - run: iverilog -s TestClock -o clock -g2012 test_clock.sv
  test:
    docker:
      - image: cranphin/iverilog
    requires:
      - build
    steps:
      - checkout
      - run: cd src
      - run: iverilog -s TestClock -o clock -g2012 test_clock.sv
      - run: ./clock