version: 2.1

jobs:
  build:
    docker:
      - image: cranphin/iverilog
    steps:
      - checkout
      - run:
          name: ビルドテスト 
          command: |
            cd src
            iverilog -s TestClock -o clock -g2012 test_clock.sv

  test:
    docker:
      - image: cranphin/iverilog
    steps:
      - checkout
      - run:
          name: ビルド＋実行
          command: |
            cd src
            iverilog -s TestClock -o clock -g2012 test_clock.sv
            ./clock

workflows:
  test:
    jobs:
      - build
      - test:
        requires:
          - build