version: 2

jobs:
  build:
    docker:
      - image: cranphin/iverilog
    steps:
      - checkout
      - run:
          name: ビルドテスト 
          command: |
            cd src
            ./build.sh

  test:
    docker:
      - image: cranphin/iverilog
    steps:
      - checkout
      - run:
          name: ビルド＋実行
          command: |
            cd src
            ./build.sh
            ./test.sh

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build