version: 2

jobs:
  build:
    docker:
      - image: cranphin/iverilog
    steps:
      - checkout
      - run:
          name: ビルドテスト 
          command: |
            cd src
            iverilog -s TestClock -o clock -g2012 test_clock.sv
            iverilog -s TestAdder -o clock -g2012 test_adder.sv

  test:
    docker:
      - image: cranphin/iverilog
    steps:
      - checkout
      - run:
          name: ビルド＋実行
          command: |
            cd src
            iverilog -s TestClock -o clock -g2012 test_clock.sv
            ./clock
            iverilog -s TestAdder -o clock -g2012 test_adder.sv
            ./adder

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build